### ISSUE TITLE
Indirect recursive call counting varies with function name

### ISSUE THREAD

**Issue by SiriusStarr** [jfmengels/elm-review-cognitive-complexity#5]
Per Slack convo:

When run with: `npx elm-review --template jfmengels/elm-review-cognitive-complexity/preview`:

This commit fails:  https://github.com/SiriusStarr/elm-review-no-unsorted/commit/5ee691d4c626e36d5cf078ef321c7499d062e1d2

This commit passes:  https://github.com/SiriusStarr/elm-review-no-unsorted/commit/a6a1f8eb45b7e9ef40d8267e8bf5842d686f5576

This seems to be due to more indirect recursive calls being detected in the former case.

**Comment by jfmengels** [comment]
Fixed by #6
